name: Build and deploy Node.js app to Azure Web App - app-infra-fyochat-dev-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and build backend
        working-directory: ./api
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          cd api
          zip -r release.zip ./*
          mv release.zip ${{ github.workspace }}/release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
